### ISSUE TITLE
Better formatting for main instructions

### ISSUE THREAD

**Issue by LMH01** [LMH01/alpha_tui#2]
Add optional mode (or make it default and it can be disabled) that the instructions are better formatted.

Labels, code and comments should be aligned to each other.
Example:

```
loop:           a0 := 5               // Assign value 5 to accumulator a0
another_label:  p(h) := 10            // ...
```

## Tasks
- [x] Implement base formatting
- [x] Add cli parameter to disable new formatting
- [x] Add cli parameter with which the new formatting can be written to the source file
- [x] Check if full line comments are still working

**Comment by LMH01** [comment]
Formatting now works and is set to enabled by default. Now the CLI parameter to disable it has to be added
