### ISSUE TITLE
Implement sandbox mode

### ISSUE THREAD

**Issue by LMH01** [LMH01/alpha_tui#33]
After #24 was implemented it is now possible to run a custom instruction while a program is loaded. 

This should make it quite easy to implement a kind of sandbox mode, where no program is loaded actively and where some things are changed:

This should be done the following way:

- The current run custom instruction popup will be placed below the main instruction window and will always remain open
- The main instruction window is empty when opened and no program needs to be supplied to the program
- Entered custom commands are appended to the main instruction window (newest at the bottom, like a terminal)

I will have to see how and if GOTO, CALL and IF commands and their labels can be implemented, but I currently don't see a good way on how that could work nicely.

## TODO

- [x] update documentation to include picture of this new sandbox mode (main readme (or maybe in new documentation page?))
- [x] add example on how this sandbox mode can be used to demo gif
- [x] hide breakpoint and next instruction windows
- [x] implement function
- [x] check if all commands that are marked as always available work with this new sandbox command. Commands that don't do anything, should be moved to the subcommand (if argument is applicable to multiple subcomands, but not sandbox, maybe I can utilize argument groups to be able to define them once and use them in multiple subcommands)

**Comment by LMH01** [comment]
Maybe an idea to get the label things working would be to provide a new window element where a couple of lines of code can be placed that can be used to run goto, call and go instructions against. The instructions in the window could be set when the sandbox mode is opened, either explicitly using a cli flag or a predefined value if the cli flag is absent.

I however think that doing so could be a bit of work to implement.

**Comment by LMH01** [comment]
Subcommands that should not be marked global anymore and should only be allowed for load and check:

- --disable-memory-detection
- --allowed-comparisons
- --allowed-operations
- --allowed-instructions
- --enable-gamma-accumulator

**Comment by LMH01** [comment]
implemented and will be included in the next release
