### ISSUE TITLE
Add support for index memory cells

### ISSUE THREAD

**Issue by LMH01** [LMH01/alpha_tui#4]
Index memory cells should be supported. For that a new section named "Index Memory Cells" should be added below the current "Memory Cells" section.

It would be nice if the tui section could somehow be merged with the memory cells section (so that booth lists are surrounded with the same line).

## How it works
```
p(6) := 42
a1 := 30
 y := 5
 loop:
 p(y) := 5
 if y = a1 goto end
 y := y + 1
 goto loop
 end:

Nach Zeile 1
 x |  p(x)
---|------
 5 |     
 6 |   42
 7 |     
 8 |     
.. |  ....
30 |     

Nach Programm Ende 
 x |  p(x)
---|------
 5 |     5
 6 |     5
 7 |     5
 8 |     5
.. |  ....
30 |     5
```

## Tasks
- [x] Add documentation for how index memory cells work
- [x] Parsing
- [x] Runtime: target type support - implement that value can be assigned to index memory cell
- [x] Runtime: value type support - implement that value can be read from index memory cell
- [x] Value struct - add IndexMemoryCell variant
- [x] Add support for alpha accumualtors
- [x] Add support for gamma (y or $\gamma$) accumulator, gamma will just be a specially named accumulator. Gamma register should only be present in the accumulator ui list, when it is actually used, related to #10 
- [x] Add tests
- [x] Add ui support
- [x] Implement automatic recognition for gamma, accumulators and memory cells in index memory cell instructions
- [x] Modify flag with which values can be loaded into memory cells to support loading values into index memory cells

**Comment by LMH01** [comment]
I have decided to display the index memory cells in the same list as the normal memory cells instead of creating a new section.
