### ISSUE TITLE
Make allowed operations and allowed comparisons configurable in instruction config file

### ISSUE THREAD

**Issue by LMH01** [LMH01/alpha_tui#72]
See title.

## TODO

- [x] Add more tests
    - [x] Check if data types left out of allowed instructions file are working (that they can be left out)
    - [x] Test if all operations/comparisons can be forbidden by providing an empty array
- [x] Update documentation
    - [x] How --allowed-instructions-file interacts with --allowed-comparisons and --allowed-operations (that operations/comparisons allowed are merged)
    - [x] That all values in instruction-config file can be null, to just limit a specific type
    - [x] Example file
- [x] (Decide how to) handle case when --allowed-instructions-file is provided where allowed comparisons and operations are set in and where --allowed-comparisons/--allowed-operations is provided as command line argument. I'd say that operations/comparisons are merged and if the are allowed in either file/command they are accepted.

**Comment by LMH01** [comment]
I'd say that the feature is ready for release.
