### ISSUE TITLE
Make theming editable

### ISSUE THREAD

**Issue by LMH01** [LMH01/alpha_tui#77]
The theming of the app should be editable.

## TODO

- [x] add example theme file
    - [x] also add files for each theme, so that they could be modified
- [x] add cli option to load theme from json file
- [x] add cli option to load build in theme (default_old and dracula)
- [x] make theme get auto loaded if a theme file exists in config directory
    - [x] Is dependent on platform, under linux it will be in `~/.config/alpha_tui/theme.json`, in windows it will be `{FOLDERID_Profile}/.config/alpha_tui/theme.json`
    - [x] theme provided via cli option overwrites default theme in this config directory
- [x] fully implement dracula theme (mean there will be more fields to be editable)
- [x] update documentation
    - [x] how to write custom theme (show example theme file)
    - [x] that theme can be placed in `.config/alpha_tui/theme.json` and that theme is loaded automatically from there

**Comment by LMH01** [comment]
completed and will be included in the next updated
